### ISSUE TITLE
Syncronize input mode when joining.

### ISSUE THREAD

**Issue by Beanow** [Beanow/vrchat-ime-demo#1]
Currently the default state for everyone is `EN` mode and a blank input / log.
The biggest issue with this is when a keyboard was left in `JP` mode by someone else before joining.
The input will then be seen differently.

The input mode should be somehow tracked / buffered and applied when joining to keep synchronized.

**Comment by knt2nd** [comment]
It would be good to toggle the enter key in local whether EN mode or JP mode. Then the WebPanel can get the current input mode. I think that's the best way because only one message would be messed up.

**Comment by Beanow** [comment]
Thank you for the suggestion. Yes I had a similar idea, tracking the state using buffered events outside the browser and submitting it somehow.

If we can make the client also send this to the browser when they join though it would be better I think. Especially for the scenario when a keyboard is left in JP mode, but not in use. A newly joining person might have no idea it will show japanese for other people for the first message.

**Comment by Beanow** [comment]
This is now resolved by VRC's buffer once, several animations and the `javascript:mode('JP')` style calls.
