### ISSUE TITLE
Check out Anthy as an open-source alternative to Google suggestions

### ISSUE THREAD

**Issue by Beanow** [Beanow/vrchat-ime-demo#4]
Anthy is a Japanese IME for Linux.
https://osdn.net/projects/anthy/

It seems to use a dictionary that you can further personalize.

We may be able to use the built-in dictionary and/or code to make a Javascript port, or run this on a remote server. As an alternative to Google's APIs.

The main engine is written in C though. So rewriting this to JavaScript would be quite a project.

See also #7

**Comment by knt2nd** [comment]
I just found the article about Japanese input on Oculus Go. http://www.itmedia.co.jp/news/articles/1806/13/news106.html
It seems that the bookmarklet uses Google CGI API for Japanese Input https://www.google.co.jp/ime/cgiapi.html which is public API.
How about it?

**Comment by Beanow** [comment]
Interesting, this transliteration API and the API I'm using are part of the same tools.
Where does it say you can use the API though? :/
Because if it's allowed we can probably use the current one too.

**Comment by knt2nd** [comment]
Here is ToS. https://developers.google.com/transliterate/terms
I didn't see in detail but it seems okay.
"You are allowed to use the API only to display" means just "Don't save it" right?
